"""
Paper Table I: combined KITTI + nuScenes comparison on the Seoul V2X trace,
in the original manuscript format (Dataset | Method | Acc | Poor Acc | Loss |
Gap | Rounds@tau | Tx@tau), from results/metrics_v2x_real_{kitti,nuscenes}.npz.

Output: new_result/tab_seoul_combined.tex
Variant (Poor Acc relabelled High-Demand Acc, Gap column dropped):
        new_result/tab_seoul_combined_highdemand.tex
"""

import os
import numpy as np
from .make_tables import SCHEMES, FRAMEWORK, PUBLISHED, DISPLAY, TAIL, \
    _load, NR


def _seed_curves(res_s, key):
    """Per-seed curves [n_seeds, K]; falls back to the seed-mean curve for
    npz files predating the *_all keys."""
    if key + "_all" in res_s:
        return np.asarray(res_s[key + "_all"])
    return res_s[key][None, :]


def _stats(res):
    """All entries mean ± std over per-seed statistics."""
    schemes = [x for x in SCHEMES if x in res]
    tau = 0.95 * max(res[s]["acc"][-1] for s in schemes)
    out = {}
    for s in schemes:
        acc_c = _seed_curves(res[s], "acc")
        poor_c = _seed_curves(res[s], "poor")
        loss_c = _seed_curves(res[s], "vloss")
        tx_c = _seed_curves(res[s], "tx")
        mb_c = _seed_curves(res[s], "txmb")
        acc = acc_c[:, -TAIL:].mean(1)
        poor = poor_c[:, -TAIL:].mean(1)
        loss = loss_c[:, -TAIL:].mean(1)
        gap = acc - poor
        # useful-delivery ratio: demand-weighted share of need served by an
        # encoder stronger than the receiver's own; whole-run mean (the
        # delivery mechanism matters during convergence, not at the tail)
        udel = _seed_curves(res[s], "usat").mean(1)
        rounds, cumtx, cummb = [], [], []
        for a, t, m in zip(acc_c, tx_c, mb_c):
            reach = a >= tau
            if reach.any():
                r = int(np.argmax(reach)) + 1
                rounds.append(r)
                cumtx.append(float(t[:r].sum()))
                cummb.append(float(m[:r].sum()) / 1024.0)
        reached_all = len(rounds) == acc_c.shape[0]
        out[s] = dict(
            acc=acc.mean(), acc_sd=acc.std(),
            poor=poor.mean(), poor_sd=poor.std(),
            loss=loss.mean(), loss_sd=loss.std(),
            gap=gap.mean(), gap_sd=gap.std(),
            udel=udel.mean(), udel_sd=udel.std(),
            rounds=(np.mean(rounds), np.std(rounds)) if reached_all else None,
            cumtx=(np.mean(cumtx), np.std(cumtx)) if reached_all else None,
            cummb=(np.mean(cummb), np.std(cummb)) if reached_all else None,
            totaltx=int(tx_c.sum(1).mean()),
            totalmb=float(mb_c.sum(1).mean()) / 1024.0)
    return out


def _deadline_stats(tag, deadlines):
    """P(useful delivery to a high-demand vehicle within d rounds), windowed
    over all round starts; seed-mean per scheme. Reads the event-level npz
    written by sim.run_v2x_real (out_name=..._events.npz)."""
    path = f"results/metrics_v2x_real_{tag}_events.npz"
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"{path} missing - run sim.run_v2x_real with "
            f"out_name='metrics_v2x_real_{tag}_events.npz' first")
    z = np.load(path)
    out = {}
    for s in SCHEMES:
        if f"{s}__udeliv_all" not in z.files:
            continue
        per_seed = []
        for U, pm in zip(z[f"{s}__udeliv_all"], z[f"{s}__pmask_all"]):
            Up = U[:, pm]
            K = Up.shape[0]
            per_seed.append([np.array([Up[t:t + d].any(0)
                                       for t in range(K - d + 1)]).mean()
                             for d in deadlines])
        out[s] = np.array(per_seed).mean(0)          # one value per deadline
    return out


def _pm(v, sd, bold):
    c = f"{100*v:.1f} $\\pm$ {100*sd:.1f}"
    return f"\\textbf{{{c}}}" if bold else c


def _num(v, bold, fmt="{}"):
    c = fmt.format(v)
    return f"\\textbf{{{c}}}" if bold else c


def make(out_path="new_result/tab_seoul_combined.tex",
         poor_header=r"\textsc{Poor Acc}", include_gap=True,
         include_udel=False, deadlines=(), colsep="5pt", font=None,
         npz_fmt="results/metrics_v2x_real_{}.npz",
         label="tab:seoul_results", comm_gb=False):
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    ncol = 7 + int(include_gap) + int(include_udel) + len(deadlines)
    lines = []
    a = lines.append
    a(r"% Auto-generated by sim/face_main_table.py from the unified-protocol")
    a(r"% Seoul V2X runs (all schemes share the Sec. III encoder lifecycle).")
    a(r"\begin{table*}[t]")
    a(r"    \centering")
    a(r"    \caption{Overall performance comparison on KITTI and nuScenes.}")
    a(r"    \label{%s}" % label)
    if font:
        a(r"    " + font)
    a(r"    \renewcommand{\arraystretch}{1.15}")
    a(r"    \setlength{\tabcolsep}{%s}" % colsep)
    a(r"    \begin{tabular}{" + "|".join(["c"] * ncol) + "}")
    a(r"        \hline")
    a(r"        \textsc{Dataset} & \textsc{Method} & \textsc{Acc} & "
      + poor_header)
    mid = [r"\textsc{Loss}"]
    if include_gap:
        mid.append(r"\textsc{Gap}")
    if include_udel:
        # "useful delivery" is the Sec. III-D term (Eq. 12 context)
        mid.append(r"\shortstack{\textsc{Useful-Delivery}\\"
                   r"\textsc{Ratio (\%)}}")
    for d in deadlines:
        # P(useful delivery to a high-demand vehicle within d rounds);
        # same @-convention as Rounds@tau, matches the deadline figure
        mid.append(r"\shortstack{\textsc{Delivery}\\@$d{=}%d$}" % d)
    mid.append(r"\textsc{Rounds@$\tau$}")
    a(r"        & " + " & ".join(mid))
    a(r"        & \shortstack{\textsc{Comm@$\tau$}\\(GB)} \\" if comm_gb
      else r"        & \textsc{Tx@$\tau$} \\")
    a(r"        \hline")
    for tag, label in (("kitti", "KITTI"), ("nuscenes", "nuScenes")):
        res = _load(npz_fmt.format(tag))
        st = _stats(res)
        schemes = [x for x in SCHEMES if x in st]
        dl = _deadline_stats(tag, deadlines) if deadlines else {}
        dl_best = [max(dl[s][i] for s in schemes if s in dl)
                   for i in range(len(deadlines))] if deadlines else []
        best = dict(
            acc=max(st[s]["acc"] for s in schemes),
            poor=max(st[s]["poor"] for s in schemes),
            loss=min(st[s]["loss"] for s in schemes),
            gap=min(st[s]["gap"] for s in schemes),
            udel=max(st[s]["udel"] for s in schemes),
            rounds=min((st[s]["rounds"][0] for s in schemes
                        if st[s]["rounds"]), default=None),
            cumtx=min((st[s]["cumtx"][0] for s in schemes
                       if st[s]["cumtx"]), default=None),
            cummb=min((st[s]["cummb"][0] for s in schemes
                       if st[s]["cummb"]), default=None))
        a(f"        \\multirow{{{len(schemes)}}}{{*}}"
          f"{{\\textsc{{{label}}}}}")
        for s in schemes:
            d = st[s]
            # manuscript Table I shape: Acc / Poor with +-std, Loss (3 dec)
            # and Gap (1 dec) as plain numbers, integer Rounds@tau / Tx@tau
            cells = [
                f"\\textsc{{{DISPLAY.get(s, s)}}}",
                _pm(d["acc"], d["acc_sd"], abs(d["acc"] - best["acc"]) < 1e-9),
                _pm(d["poor"], d["poor_sd"],
                    abs(d["poor"] - best["poor"]) < 1e-9),
                _num(f"{d['loss']:.3f}",
                     abs(d["loss"] - best["loss"]) < 1e-9),
            ]
            if include_gap:
                cells.append(_num(f"{100*d['gap']:.1f}",
                                  abs(d["gap"] - best["gap"]) < 1e-9))
            if include_udel:
                cells.append(_num(f"{100*d['udel']:.1f}",
                                  abs(d["udel"] - best["udel"]) < 1e-9))
            for di in range(len(deadlines)):
                cells.append(_num(f"{100*dl[s][di]:.1f}",
                                  abs(dl[s][di] - dl_best[di]) < 1e-9))
            if d["rounds"] is None:
                cells += [NR, (f"$>{d['totalmb']:.1f}$" if comm_gb
                               else f"$>{d['totaltx']}$")]
            elif comm_gb:
                cells += [
                    _num(f"{d['rounds'][0]:.0f}",
                         d["rounds"][0] == best["rounds"]),
                    _num(f"{d['cummb'][0]:.1f}",
                         d["cummb"][0] == best["cummb"])]
            else:
                cells += [
                    _num(f"{d['rounds'][0]:.0f}",
                         d["rounds"][0] == best["rounds"]),
                    _num(f"{d['cumtx'][0]:.0f}",
                         d["cumtx"][0] == best["cumtx"])]
            a("        & " + " & ".join(cells) + r" \\")
            if s in (FRAMEWORK[-1], PUBLISHED[-1]):
                a(f"        \\cline{{2-{ncol}}}" if s != schemes[-1] else "")
        a(r"        \hline")
    a(r"    \end{tabular}")
    a(r"\end{table*}")
    with open(out_path, "w") as f:
        f.write("\n".join(x for x in lines if x != "") + "\n")
    print("wrote", out_path)


if __name__ == "__main__":
    make()
    make("new_result/tab_seoul_combined_highdemand.tex",
         poor_header=r"\textsc{High-Demand Acc}", include_gap=False)
    make("new_result/tab_seoul_combined_highdemand_udel.tex",
         poor_header=r"\shortstack{\textsc{High-Demand}\\\textsc{Acc}}",
         include_gap=False, include_udel=True, deadlines=(5, 20),
         colsep="4pt", font=r"\footnotesize", comm_gb=True)
    make("new_more_seed/tab_seoul_combined_8seed.tex",
         poor_header=r"\shortstack{\textsc{High-Demand}\\\textsc{Acc}}",
         include_gap=False, include_udel=True, deadlines=(),
         colsep="4.5pt", font=r"\footnotesize",
         npz_fmt="new_more_seed/metrics_v2x_real_{}_8seed.npz",
         label="tab:seoul_results_8seed", comm_gb=True)
