"""
Generate the FACE component-ablation LaTeX table (new system model) from the
sweep logs written by sim/face_ablation.py. Works on partial logs (fewer
seeds) and regenerates the final 3-seed table when the sweeps complete.

Output: new_result/tab_face_ablation.tex
"""

import os
import re
import numpy as np

ROW = re.compile(r"\[seed (\d+)\] (.{18}) acc ([\d.]+) poor ([\d.]+) "
                 r"tx/rd ([\d.]+) MB/rd ([\d.]+) beyond (\d+)")

# variant -> (paper label, disabled mechanism in paper notation)
LABELS = {
    "FACE (full)":       (r"\textbf{FACE (full)}", ""),
    "w/o relay ferrying": (r"w/o encoder ferrying",
                           r"$\mathcal A_{ij}(t)$ own versions only"),
    "w/o demand":        (r"w/o demand awareness",
                          r"$\widehat v_{j,x}\!\equiv\!\mathrm{const}$ in \eqref{eq:transfer_advantage}"),
    "w/o future value":  (r"w/o future-contact value",
                          r"$F_{a,x}\!\equiv\!0$ in \eqref{eq:forwarding_potential}"),
    "w/o coverage":      (r"w/o residual coverage",
                          r"$\Omega_{z,x}^{(h)}\!\equiv\!1$ in \eqref{eq:residual_coverage}"),
    "w/o tickets":       (r"w/o replication tokens",
                          r"$K_x\!=\!\infty$ in \eqref{eq:copy_cap}"),
    "w/o consume mode":  (r"w/o consume-only transfers",
                          r"$a^{\mathrm{con}}\!\equiv\!0$ in \eqref{eq:bundle_knapsack}"),
    "w/o ridge gain":    (r"w/o reward prediction",
                          r"mean bandit for \eqref{eq:predicted_gain}"),
    "w/o cache refresh": (r"w/o coverage-aware refresh",
                          r"LRU replaces \eqref{eq:cache_refresh}"),
}
ORDER = list(LABELS)
# key variants for the paper table (INFOCOM space budget): the components
# with material end-to-end contribution; the near-zero rows (residual
# coverage, value-weighted split, gain prediction) are text-only mentions
KEY = ["FACE (full)", "w/o relay ferrying", "w/o tickets",
       "w/o consume mode", "w/o cache refresh", "w/o demand",
       "w/o future value"]


def _parse(path):
    out = {}
    if not os.path.exists(path):
        return out
    for line in open(path):
        m = ROW.search(line)
        if m:
            sd, name = m.group(1), m.group(2).strip()
            vals = [float(g) for g in m.groups()[2:]]
            out.setdefault(name, {})[sd] = vals   # last write per (name, seed)
    return out


def _cell(rows, idx, pct=True, best=None):
    arr = np.array([v[idx] for v in rows.values()])
    m, s = arr.mean(), arr.std()
    if pct:
        txt = f"{100*m:.1f} $\\pm$ {100*s:.1f}"
    else:
        txt = f"{m:.0f}"
    if best is not None and abs(m - best) < 1e-9:
        txt = r"\textbf{" + txt + "}"
    return txt, m


def make(log="results/face_abl_uniform.log",
         out_path="new_result/tab_face_ablation.tex", keys=None):
    """Single-scenario ablation table (uniform ECV placement, matching the
    main-comparison setup); `keys` selects the variants (default: KEY)."""
    res = _parse(log)
    order = [n for n in (keys or KEY) if n in LABELS]
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    seeds_note = sorted({len(v) for v in res.values()})

    lines = []
    a = lines.append
    a(r"% Auto-generated by sim/face_abl_table.py from the FACE component")
    a(r"% ablation on the Seoul-Gangnam V2X trace (abstract MDFL backend,")
    a(r"% 250 rounds, region-partitioned encoder carriers).")
    a(r"% seeds per variant: " + str(seeds_note))
    a(r"\begin{table}[t]")
    a(r"\centering")
    a(r"\caption{Component ablation of FACE on the Seoul V2X trace.}")
    a(r"\label{tab:face_ablation}")
    a(r"\renewcommand{\arraystretch}{1.12}")
    a(r"\setlength{\tabcolsep}{4.5pt}")
    a(r"\scriptsize")
    a(r"\begin{tabular}{l|cc|c}")
    a(r"\hline")
    a(r"\textsc{Variant} & \textsc{Acc} & \textsc{Poor Acc} & "
      r"\textsc{Comm. (MB/rd)} \\")
    a(r"\hline")
    best = max(np.mean([v[0] for v in res[n].values()])
               for n in order if n in res) if res else None
    for name in order:
        lbl, mech = LABELS[name]
        full_lbl = lbl if not mech else f"{lbl} ({mech})"
        if name in res:
            acc, _ = _cell(res[name], 0, best=best)
            poor, _ = _cell(res[name], 1)
            mbs = [v[3] for v in res[name].values()]
            mb = f"{np.mean(mbs):.0f} $\\pm$ {np.std(mbs):.0f}"
            cells = [full_lbl, acc, poor, mb]
        else:
            cells = [full_lbl, "--", "--", "--"]
        a(" & ".join(cells) + r" \\")
        if name == "FACE (full)":
            a(r"\hline")
    a(r"\hline")
    a(r"\end{tabular}")
    a(r"\vspace{-1.5mm}")
    a(r"\end{table}")
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", out_path, "| seeds per variant:", seeds_note)
    return out_path


if __name__ == "__main__":
    make()
