"""
Generate the FACE component-ablation LaTeX table (new system model) from the
sweep logs written by sim/face_ablation.py. Works on partial logs (fewer
seeds) and regenerates the final 3-seed table when the sweeps complete.

Output: new_result/tab_face_ablation.tex
"""

import os
import re
import numpy as np

ROW = re.compile(r"\[seed (\d+)\] (.{18}) acc ([\d.]+) poor ([\d.]+) "
                 r"tx/rd ([\d.]+) MB/rd ([\d.]+) beyond (\d+)")

# variant -> (paper label, mechanism disabled)
LABELS = {
    "FACE (full)":       (r"\textbf{FACE (full)}", ""),
    "w/o relay ferrying": (r"w/o encoder ferrying",
                           r"relay cache fwd.\ disabled"),
    "w/o demand":        (r"w/o demand awareness",
                          r"$\widehat v_{j,x}(t)\!\equiv\!\mathrm{const}$ in \eqref{eq:transfer_advantage}"),
    "w/o future value":  (r"w/o future-contact value",
                          r"$F_{a,x}\!\equiv\!0$ \eqref{eq:forwarding_potential}"),
    "w/o coverage":      (r"w/o residual coverage",
                          r"$\Omega_{z,x}^{(h)}\!\equiv\!1$ \eqref{eq:residual_coverage}"),
    "w/o tickets":       (r"w/o copy tickets",
                          r"$K_x\!=\!\infty$ \eqref{eq:ticket_update}"),
    "w/o ridge gain":    (r"w/o optimistic gain pred.",
                          r"mean estimate for \eqref{eq:predicted_gain}"),
    "w/o cache refresh": (r"w/o coverage-aware refresh",
                          r"LRU instead of \eqref{eq:cache_refresh}"),
}
ORDER = list(LABELS)


def _parse(path):
    out = {}
    if not os.path.exists(path):
        return out
    for line in open(path):
        m = ROW.search(line)
        if m:
            sd, name = m.group(1), m.group(2).strip()
            vals = [float(g) for g in m.groups()[2:]]
            out.setdefault(name, {})[sd] = vals   # last write per (name, seed)
    return out


def _cell(rows, idx, pct=True, best=None):
    arr = np.array([v[idx] for v in rows.values()])
    m, s = arr.mean(), arr.std()
    if pct:
        txt = f"{100*m:.1f} $\\pm$ {100*s:.1f}"
    else:
        txt = f"{m:.0f}"
    if best is not None and abs(m - best) < 1e-9:
        txt = r"\textbf{" + txt + "}"
    return txt, m


def make(uni_log="results/face_abl_uniform.log",
         part_log="results/face_abl_part.log",
         out_path="new_result/tab_face_ablation.tex"):
    uni, part = _parse(uni_log), _parse(part_log)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    n_seeds = {len(v) for v in list(uni.values()) + list(part.values())}
    seeds_note = sorted(n_seeds)

    lines = []
    a = lines.append
    a(r"% Auto-generated by sim/face_abl_table.py from the FACE component")
    a(r"% ablation on the Seoul-Gangnam V2X trace (abstract MDFL backend,")
    a(r"% 250 rounds, K_x=6 tickets).")
    a(r"% seeds per variant: " + str(seeds_note))
    a(r"\begin{table}[t]")
    a(r"\centering")
    a(r"\caption{Component ablation of FACE on the Seoul V2X trace: uniform "
      r"and region-partitioned encoder-carrier (ECV) placement.}")
    a(r"\label{tab:face_ablation}")
    a(r"\renewcommand{\arraystretch}{1.12}")
    a(r"\setlength{\tabcolsep}{3.4pt}")
    a(r"\scriptsize")
    a(r"\begin{tabular}{l|cc|cc|c}")
    a(r"\hline")
    a(r"\multirow{2}{*}{\textsc{Variant}} & "
      r"\multicolumn{2}{c|}{\textsc{Uniform ECVs}} & "
      r"\multicolumn{2}{c|}{\textsc{Partitioned ECVs}} & "
      r"\textsc{Comm.} \\")
    a(r" & \textsc{Acc} & \textsc{Poor Acc} & \textsc{Acc} & "
      r"\textsc{Poor Acc} & \textsc{(MB/rd)} \\")
    a(r"\hline")
    best_u = max(np.mean([v[0] for v in uni[n].values()])
                 for n in ORDER if n in uni) if uni else None
    best_p = max(np.mean([v[0] for v in part[n].values()])
                 for n in ORDER if n in part) if part else None
    for name in ORDER:
        lbl, _ = LABELS[name]
        cells = [lbl]
        for src, best in ((uni, best_u), (part, best_p)):
            if name in src:
                acc, _ = _cell(src[name], 0, best=best)
                poor, _ = _cell(src[name], 1)
                cells += [acc, poor]
            else:
                cells += ["--", "--"]
        if name in uni or name in part:
            mbs = [v[3] for s in (uni, part) if name in s
                   for v in s[name].values()]
            cells.append(f"{np.mean(mbs):.0f}")
        else:
            cells.append("--")
        a(" & ".join(cells) + r" \\")
        if name == "FACE (full)":
            a(r"\hline")
    a(r"\hline")
    a(r"\end{tabular}")
    a(r"\vspace{-1.5mm}")
    a(r"\end{table}")
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", out_path, "| seeds per variant:", seeds_note)
    return out_path


if __name__ == "__main__":
    make()
