"""
Paper Table I: combined KITTI + nuScenes comparison on the Seoul V2X trace,
in the original manuscript format (Dataset | Method | Acc | Poor Acc | Loss |
Gap | Rounds@tau | Tx@tau), from results/metrics_v2x_real_{kitti,nuscenes}.npz.

Output: new_result/tab_seoul_combined.tex
"""

import os
import numpy as np
from .make_tables import SCHEMES, FRAMEWORK, PUBLISHED, DISPLAY, TAIL, \
    _load, NR


def _stats(res):
    schemes = [x for x in SCHEMES if x in res]
    tau = 0.95 * max(res[s]["acc"][-1] for s in schemes)
    out = {}
    for s in schemes:
        acc = res[s]["acc"][-TAIL:].mean()
        acc_sd = res[s]["acc_std"][-TAIL:].mean()
        poor = res[s]["poor"][-TAIL:].mean()
        poor_sd = res[s]["poor_std"][-TAIL:].mean()
        loss = res[s]["vloss"][-TAIL:].mean()
        reached = res[s]["acc"] >= tau
        rounds = int(np.argmax(reached)) + 1 if reached.any() else None
        tx = res[s]["tx"]
        cumtx = int(tx[:rounds].sum()) if rounds else None
        out[s] = dict(acc=acc, acc_sd=acc_sd, poor=poor, poor_sd=poor_sd,
                      loss=loss, gap=acc - poor, rounds=rounds, cumtx=cumtx,
                      totaltx=int(tx.sum()))
    return out


def _pm(v, sd, bold):
    c = f"{100*v:.1f} $\\pm$ {100*sd:.1f}"
    return f"\\textbf{{{c}}}" if bold else c


def _num(v, bold, fmt="{}"):
    c = fmt.format(v)
    return f"\\textbf{{{c}}}" if bold else c


def make(out_path="new_result/tab_seoul_combined.tex"):
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    lines = []
    a = lines.append
    a(r"% Auto-generated by sim/face_main_table.py from the unified-protocol")
    a(r"% Seoul V2X runs (all schemes share the Sec. III encoder lifecycle).")
    a(r"\begin{table*}[t]")
    a(r"    \centering")
    a(r"    \caption{Overall performance comparison on KITTI and nuScenes.}")
    a(r"    \label{tab:seoul_results}")
    a(r"    \renewcommand{\arraystretch}{1.15}")
    a(r"    \setlength{\tabcolsep}{5pt}")
    a(r"    \begin{tabular}{c|c|c|c|c|c|c|c}")
    a(r"        \hline")
    a(r"        \textsc{Dataset} & \textsc{Method} & \textsc{Acc} & "
      r"\textsc{Poor Acc}")
    a(r"        & \textsc{Loss} & \textsc{Gap} & \textsc{Rounds@$\tau$}")
    a(r"        & \textsc{Tx@$\tau$} \\")
    a(r"        \hline")
    for tag, label in (("kitti", "KITTI"), ("nuscenes", "nuScenes")):
        res = _load(f"results/metrics_v2x_real_{tag}.npz")
        st = _stats(res)
        schemes = [x for x in SCHEMES if x in st]
        best = dict(
            acc=max(st[s]["acc"] for s in schemes),
            poor=max(st[s]["poor"] for s in schemes),
            loss=min(st[s]["loss"] for s in schemes),
            gap=min(st[s]["gap"] for s in schemes),
            rounds=min((st[s]["rounds"] for s in schemes
                        if st[s]["rounds"]), default=None),
            cumtx=min((st[s]["cumtx"] for s in schemes
                       if st[s]["cumtx"]), default=None))
        a(f"        \\multirow{{{len(schemes)}}}{{*}}"
          f"{{\\textsc{{{label}}}}}")
        for grp_end, s in [(FRAMEWORK[-1], s) for s in schemes]:
            d = st[s]
            cells = [
                f"\\textsc{{{DISPLAY.get(s, s)}}}",
                _pm(d["acc"], d["acc_sd"], abs(d["acc"] - best["acc"]) < 1e-9),
                _pm(d["poor"], d["poor_sd"],
                    abs(d["poor"] - best["poor"]) < 1e-9),
                _num(f"{d['loss']:.3f}",
                     abs(d["loss"] - best["loss"]) < 1e-9),
                _num(f"{100*d['gap']:.1f}",
                     abs(d["gap"] - best["gap"]) < 1e-9),
            ]
            if d["rounds"] is None:
                cells += [NR, f"$>{d['totaltx']}$"]
            else:
                cells += [_num(d["rounds"], d["rounds"] == best["rounds"]),
                          _num(d["cumtx"], d["cumtx"] == best["cumtx"])]
            a("        & " + " & ".join(cells) + r" \\")
            if s in (FRAMEWORK[-1], PUBLISHED[-1]):
                a(r"        \cline{2-8}" if s != schemes[-1] else "")
        a(r"        \hline")
    a(r"    \end{tabular}")
    a(r"\end{table*}")
    with open(out_path, "w") as f:
        f.write("\n".join(x for x in lines if x != "") + "\n")
    print("wrote", out_path)


if __name__ == "__main__":
    make()
