"""Table for the second (late-night) Seoul V2X window: KITTI + nuScenes,
6 schemes, 3 seeds, same format as Table I's high-demand + useful-delivery
variant (sim/face_main_table.py). Deadline stats come from the night npz
itself (udeliv/pmask are recorded in the same file). Datasets whose npz is
not present yet are skipped.

Run:  python3 newnewdata/make_night_table.py
Out:  newnewdata/tab_seoul_night.tex
"""
import os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
os.chdir(ROOT)

import numpy as np
from sim.make_tables import SCHEMES, FRAMEWORK, PUBLISHED, DISPLAY, NR, _load
from sim.face_main_table import _stats, _pm, _num

DATASETS = [
    ("newnewdata/metrics_v2x_real_kitti_night.npz",
     r"\shortstack{\textsc{KITTI}\\\textsc{(night)}}"),
    ("newnewdata/metrics_v2x_real_nuscenes_night.npz",
     r"\shortstack{\textsc{nuScenes}\\\textsc{(night)}}"),
]
OUT = "newnewdata/tab_seoul_night.tex"
DEADLINES = (5, 20)
NCOL = 10


def _deadline_stats(path, deadlines):
    z = np.load(path)
    out = {}
    for s in SCHEMES:
        if f"{s}__udeliv_all" not in z.files:
            continue
        per_seed = []
        for U, pm in zip(z[f"{s}__udeliv_all"], z[f"{s}__pmask_all"]):
            Up = U[:, pm]
            K = Up.shape[0]
            per_seed.append([np.array([Up[t:t + d].any(0)
                                       for t in range(K - d + 1)]).mean()
                             for d in deadlines])
        out[s] = np.array(per_seed).mean(0)
    return out


lines = []
a = lines.append
a(r"% Auto-generated by newnewdata/make_night_table.py from the late-night")
a(r"% Seoul V2X window (123 vehicles, 86 snapshots, Fri 23:36-23:51 KST;")
a(r"% same unified protocol, seeds, and metrics as Table I).")
a(r"\begin{table*}[t]")
a(r"    \centering")
a(r"    \caption{Performance on the second, late-night Seoul V2X window"
  r" ($123$ vehicles, weekday 23:36--23:51 KST).}")
a(r"    \label{tab:seoul_night}")
a(r"    \footnotesize")
a(r"    \renewcommand{\arraystretch}{1.15}")
a(r"    \setlength{\tabcolsep}{4pt}")
a(r"    \begin{tabular}{" + "|".join(["c"] * NCOL) + "}")
a(r"        \hline")
a(r"        \textsc{Window} & \textsc{Method} & \textsc{Acc} & "
  r"\shortstack{\textsc{High-Demand}\\\textsc{Acc}}")
a(r"        & \textsc{Loss} & \shortstack{\textsc{Useful-Delivery}\\"
  r"\textsc{Ratio (\%)}} & \shortstack{\textsc{Delivery}\\@$d{=}5$} & "
  r"\shortstack{\textsc{Delivery}\\@$d{=}20$} & \textsc{Rounds@$\tau$}")
a(r"        & \shortstack{\textsc{Comm@$\tau$}\\(GB)} \\")
a(r"        \hline")

for npz, ds_label in DATASETS:
    if not os.path.exists(npz):
        print(f"  [skip] {npz} not found")
        continue
    res = _load(npz)
    st = _stats(res)
    schemes = [x for x in SCHEMES if x in st]
    dl = _deadline_stats(npz, DEADLINES)
    dl_best = [max(dl[s][i] for s in schemes if s in dl)
               for i in range(len(DEADLINES))]
    best = dict(
        acc=max(st[s]["acc"] for s in schemes),
        poor=max(st[s]["poor"] for s in schemes),
        loss=min(st[s]["loss"] for s in schemes),
        udel=max(st[s]["udel"] for s in schemes),
        rounds=min((st[s]["rounds"][0] for s in schemes if st[s]["rounds"]),
                   default=None),
        cummb=min((st[s]["cummb"][0] for s in schemes if st[s]["cummb"]),
                  default=None))
    a(f"        \\multirow{{{len(schemes)}}}{{*}}{{{ds_label}}}")
    for s in schemes:
        d = st[s]
        cells = [
            f"\\textsc{{{DISPLAY.get(s, s)}}}",
            _pm(d["acc"], d["acc_sd"], abs(d["acc"] - best["acc"]) < 1e-9),
            _pm(d["poor"], d["poor_sd"],
                abs(d["poor"] - best["poor"]) < 1e-9),
            _num(f"{d['loss']:.3f}", abs(d["loss"] - best["loss"]) < 1e-9),
            _num(f"{100*d['udel']:.1f}",
                 abs(d["udel"] - best["udel"]) < 1e-9),
        ]
        for di in range(len(DEADLINES)):
            cells.append(_num(f"{100*dl[s][di]:.1f}",
                              abs(dl[s][di] - dl_best[di]) < 1e-9))
        if d["rounds"] is None:
            cells += [NR, f"$>{d['totalmb']:.1f}$"]
        else:
            cells += [
                _num(f"{d['rounds'][0]:.0f}",
                     d["rounds"][0] == best["rounds"]),
                _num(f"{d['cummb'][0]:.1f}",
                     d["cummb"][0] == best["cummb"])]
        a("        & " + " & ".join(cells) + r" \\")
        if s in (FRAMEWORK[-1], PUBLISHED[-1]) and s != schemes[-1]:
            a(f"        \\cline{{2-{NCOL}}}")
    a(r"        \hline")

a(r"    \end{tabular}")
a(r"\end{table*}")
with open(OUT, "w") as f:
    f.write("\n".join(lines) + "\n")
print("wrote", OUT)
